name: Build Java project

on:
  push:
    branches: [ Test ]
  pull_request:
    branches: [ Test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java (Temurin JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'    # distribución de JDK, por ejemplo 'temurin', 'zulu', etc.
          java-version: '11'         # versión de Java que necesitas
          cache: 'maven'             # opcional: cache de dependencias Maven

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Verify compilation succeeded
        run: echo "Build succeeded"
