name: 'Building Action'
description: 'Genera un pom.xml dinámico (incluyendo imágenes) y ejecuta GameController mediante Maven.'

inputs:
  distribution:
    description: 'Distribución de JDK para setup-java'
    required: true
    default: 'temurin'
  java-version:
    description: 'Versión de Java'
    required: true
    default: '11'
  build-command:
    description: >-
      Parte del comando Maven a ejecutar, p. ej.:
      'compile exec:java -Dexec.mainClass="flappybird.GameController"'.
    required: true
    default: 'compile exec:java -Dexec.mainClass="flappybird.GameController"'

runs:
  using: 'composite'
  steps:
    - name: Generar pom.xml dinámico con recursos
      shell: bash
      run: |
        cat << 'EOF' > pom.xml
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                                     http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.usuario.flappybird</groupId>
          <artifactId>flappybird</artifactId>
          <version>1.0-SNAPSHOT</version>
          <properties>
            <maven.compiler.source>11</maven.compiler.source>
            <maven.compiler.target>11</maven.compiler.target>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <junit.jupiter.version>5.9.2</junit.jupiter.version>
            <jacoco.plugin.version>0.8.10</jacoco.plugin.version>
          </properties>
          <dependencies>
            <dependency>
              <groupId>org.junit.jupiter</groupId>
              <artifactId>junit-jupiter</artifactId>
              <version>${junit.jupiter.version}</version>
              <scope>test</scope>
            </dependency>
          </dependencies>
          <build>
            <!-- Directorios de código fuente y tests personalizados -->
            <sourceDirectory>${project.basedir}/src/flappybird</sourceDirectory>
            <testSourceDirectory>${project.basedir}/tests/flappybird</testSourceDirectory>

            <!-- Incluir carpeta de imágenes como recurso -->
            <resources>
              <resource>
                <directory>${project.basedir}/images</directory>
              </resource>
            </resources>

            <plugins>
              <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                  <source>${maven.compiler.source}</source>
                  <target>${maven.compiler.target}</target>
                </configuration>
              </plugin>
              <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                  <mainClass>flappybird.GameController</mainClass>
                </configuration>
              </plugin>
              <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.plugin.version}</version>
                <executions>
                  <execution>
                    <id>prepare-agent</id>
                    <goals><goal>prepare-agent</goal></goals>
                  </execution>
                  <execution>
                    <id>report</id>
                    <phase>test</phase>
                    <goals><goal>report</goal></goals>
                  </execution>
                </executions>
              </plugin>
            </plugins>
          </build>
        </project>
        EOF
        echo "POM dinámico (incluyendo images/) generado:"
        cat pom.xml

    - name: Setup Java y Maven (cache de Maven)
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
        cache: 'maven'   # Ahora que pom.xml existe, cache funcionará sin error :contentReference[oaicite:1]{index=1}.

    - name: Mostrar versiones Java y Maven
      shell: bash
      run: |
        java -version
        mvn -v

    - name: Ejecutar build-command con Maven
      shell: bash
      run: |
        echo "Ejecutando: mvn ${{ inputs.build-command }}"
        mvn compile
        mvn ${{ inputs.build-command }}

    - name: Confirmar éxito
      if: ${{ success() }}
      shell: bash
      run: echo "Build & Run completado exitosamente."
