name: Build
description: Compile the Java project using Maven (or IntelliJ CLI).
runs:
  using: "composite"
  steps:
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Verify compilation succeeded
      run: echo "Build succeeded"
