name: 'Building Action Simple'
description: 'Compila con javac y ejecuta GameController directamente sin Maven.'

inputs:
  distribution:
    description: 'Distribución de JDK para setup-java (e.g., temurin)'
    required: true
    default: 'temurin'
  java-version:
    description: 'Versión de Java'
    required: true
    default: '11'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Mostrar Java version
      shell: bash
      run: |
        java -version

    - name: Compilar fuentes Java
      shell: bash
      run: |
        echo "Compilando fuentes de src/flappybird..."
        # Directorio de salida para .class
        mkdir -p bin
        # Encontrar todos los .java bajo src/flappybird
        files=$(find src/flappybird -name "*.java")
        if [ -z "$files" ]; then
          echo "No se encontraron archivos .java en src/flappybird"
          exit 1
        fi
        javac -d bin $files

    - name: Asegurar carpeta images disponible
      shell: bash
      run: |
        # Verificamos que exista la carpeta images en la raíz
        if [ ! -d "images" ]; then
          echo "No existe la carpeta images/ en el workspace; asegúrate de que el repositorio tenga images/"
          exit 1
        fi
        # Opcional: listar contenido
        echo "Contenido de images/:"
        ls images

    - name: Ejecutar GameController
      shell: bash
      run: |
        echo "Ejecutando GameController..."
        # Si tu GameController abre GUI, usar xvfb-run; si no, basta java.
        if command -v xvfb-run >/dev/null; then
          xvfb-run java -cp bin flappybird.GameController
        else
          java -cp bin flappybird.GameController
        fi
