name: "Doc check"
description: "Verifica que el código Java esté documentado según Doxyfile"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalar Doxygen y Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
      shell: bash

    - name: Ejecutar Doxygen en modo chequeo
      run: |
        DOXFILE="$GITHUB_WORKSPACE/Doxyfile"
        ERRFILE="$GITHUB_WORKSPACE/dox_errors.txt"

        doxygen "$DOXFILE" 2> "$ERRFILE" 1>/dev/null

        if [ -s "$ERRFILE" ]; then
          echo "❌ Errores de documentación detectados:"
          cat "$ERRFILE"
          exit 1
        else
          echo "✅ Toda la documentación cumple con Doxyfile."
        fi
      shell: bash

    - name: Subir errores (si los hay)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: doxygen-errors
        path: dox_errors.txt
        retention-days: 1
